export function createInitialState(user) {
  return {
    sets: [],
    filteredSets: [],
    seriesEntries: [],
    seriesPage: 1,
    homeMode: 'library',
    user,
    collections: [],
    setLookup: new Map(),
    cardsBySet: new Map(),
    explorerCards: [],
    explorerPage: 1,
    explorerTotalPages: 1,
    explorerTotalCount: 0,
    zoomActive: false,
    zoomScale: 2.2,
    zoomOriginX: 50,
    zoomOriginY: 50,
    zoomRaf: 0,
    activeTrigger: null,
    prefetchedLargeImages: new Set(),
    hoverPrefetchTimer: 0,
    pendingPrefetchKey: '',
    isScrollActive: false,
    scrollIdleTimer: 0,
    detailRenderToken: 0,
    collectionPromptResolve: null,
    collectionDeleteResolve: null,
    collectionCardRemoveResolve: null,
    activeModalCard: null,
    modalCollectionsToken: 0,
    controllers: { sets: null, explorer: null, setCards: new Map() },
    lazyObserver: null,
    pendingExpansionValue: '',
    activeSetId: '',
    activeCollectionId: '',
    collectionOwnershipFilter: 'all',
    detailQuery: '',
    detailKind: '',
    detailSort: 'number-asc'
  };
}

export function collectAppElements(root) {
  return {
    modeShell: root.querySelector('#mode-shell'),
    authBar: root.querySelector('#auth-bar'),
    authCopy: root.querySelector('#auth-copy'),
    authControls: root.querySelector('#auth-controls'),
    modeCaption: root.querySelector('#mode-caption'),
    modeExplorerButton: root.querySelector('#mode-explorer'),
    modeLibraryButton: root.querySelector('#mode-library'),
    modeCollectionsButton: root.querySelector('#mode-collections'),
    notFoundShell: root.querySelector('#not-found-shell'),
    notFoundHome: root.querySelector('#not-found-home'),
    notFoundLibrary: root.querySelector('#not-found-library'),
    explorerPanel: root.querySelector('#explorer-panel'),
    explorerHome: root.querySelector('#explorer-home'),
    cardQueryInput: root.querySelector('#card-query'),
    expansionFilter: root.querySelector('#expansion-filter'),
    artistFilter: root.querySelector('#artist-filter'),
    cardKindFilter: root.querySelector('#card-kind-filter'),
    elementFilter: root.querySelector('#element-filter'),
    rarityFilter: root.querySelector('#rarity-filter'),
    runFiltersButton: root.querySelector('#run-filters'),
    createCollectionButton: root.querySelector('#create-collection'),
    clearFiltersButton: root.querySelector('#clear-filters'),
    explorerStatus: root.querySelector('#explorer-status'),
    explorerResults: root.querySelector('#explorer-results'),
    explorerPager: root.querySelector('#explorer-pager'),
    explorerPageLabel: root.querySelector('#explorer-page-label'),
    explorerPrev: root.querySelector('#explorer-prev'),
    explorerNext: root.querySelector('#explorer-next'),
    libraryShell: root.querySelector('#library-shell'),
    libraryHome: root.querySelector('#library-home'),
    seriesPager: root.querySelector('#series-pager'),
    seriesPrev: root.querySelector('#series-prev'),
    seriesNext: root.querySelector('#series-next'),
    seriesPageLabel: root.querySelector('#series-page-label'),
    seriesList: root.querySelector('#series-list'),
    expansionDetail: root.querySelector('#expansion-detail'),
    detailBack: root.querySelector('#detail-back'),
    expansionSummary: root.querySelector('#expansion-summary'),
    detailSearch: root.querySelector('#detail-search'),
    detailKindFilter: root.querySelector('#detail-kind-filter'),
    detailSortFilter: root.querySelector('#detail-sort-filter'),
    detailCreateCollectionButton: root.querySelector('#detail-create-collection'),
    expansionCardsStatus: root.querySelector('#expansion-cards-status'),
    expansionCards: root.querySelector('#expansion-cards'),
    collectionsShell: root.querySelector('#collections-shell'),
    collectionsHome: root.querySelector('#collections-home'),
    collectionsStatus: root.querySelector('#collections-status'),
    collectionsList: root.querySelector('#collections-list'),
    collectionDetail: root.querySelector('#collection-detail'),
    collectionBack: root.querySelector('#collection-back'),
    collectionRename: root.querySelector('#collection-rename'),
    collectionDelete: root.querySelector('#collection-delete'),
    collectionOwnershipFilters: root.querySelector('#collection-ownership-filters'),
    collectionFilterAll: root.querySelector('#collection-filter-all'),
    collectionFilterOwned: root.querySelector('#collection-filter-owned'),
    collectionFilterMissing: root.querySelector('#collection-filter-missing'),
    collectionSummary: root.querySelector('#collection-summary'),
    collectionCardsStatus: root.querySelector('#collection-cards-status'),
    collectionCards: root.querySelector('#collection-cards'),
    status: root.querySelector('#status'),
    topStats: root.querySelector('#top-stats'),
    modal: root.querySelector('#card-modal'),
    modalClose: root.querySelector('#modal-close'),
    modalTitle: root.querySelector('#modal-title'),
    modalSubtitle: root.querySelector('#modal-subtitle'),
    modalMeta: root.querySelector('#modal-meta'),
    modalLinks: root.querySelector('#modal-links'),
    modalImage: root.querySelector('#modal-image'),
    modalImageButton: root.querySelector('#modal-image-button'),
    modalCollectionTools: root.querySelector('#modal-collection-tools'),
    modalCollectionSelect: root.querySelector('#modal-collection-select'),
    modalCollectionSubmit: root.querySelector('#modal-collection-submit'),
    modalCollectionStatus: root.querySelector('#modal-collection-status'),
    collectionNameModal: root.querySelector('#collection-name-modal'),
    collectionNameForm: root.querySelector('#collection-name-form'),
    collectionNameClose: root.querySelector('#collection-name-close'),
    collectionNameKicker: root.querySelector('#collection-name-kicker'),
    collectionNameTitle: root.querySelector('#collection-name-title'),
    collectionNameCopy: root.querySelector('#collection-name-copy'),
    collectionNameInput: root.querySelector('#collection-name-input'),
    collectionNameCancel: root.querySelector('#collection-name-cancel'),
    collectionNameSubmit: root.querySelector('#collection-name-submit'),
    collectionDeleteModal: root.querySelector('#collection-delete-modal'),
    collectionDeleteClose: root.querySelector('#collection-delete-close'),
    collectionDeleteKicker: root.querySelector('#collection-delete-kicker'),
    collectionDeleteTitle: root.querySelector('#collection-delete-title'),
    collectionDeleteCopy: root.querySelector('#collection-delete-copy'),
    collectionDeleteName: root.querySelector('#collection-delete-name'),
    collectionDeleteCancel: root.querySelector('#collection-delete-cancel'),
    collectionDeleteConfirm: root.querySelector('#collection-delete-confirm'),
    collectionCardRemoveModal: root.querySelector('#collection-card-remove-modal'),
    collectionCardRemoveClose: root.querySelector('#collection-card-remove-close'),
    collectionCardRemoveKicker: root.querySelector('#collection-card-remove-kicker'),
    collectionCardRemoveTitle: root.querySelector('#collection-card-remove-title'),
    collectionCardRemoveCopy: root.querySelector('#collection-card-remove-copy'),
    collectionCardRemoveName: root.querySelector('#collection-card-remove-name'),
    collectionCardRemoveCancel: root.querySelector('#collection-card-remove-cancel'),
    collectionCardRemoveConfirm: root.querySelector('#collection-card-remove-confirm')
  };
}

export function bootstrapApp({
  setAuthChangeHandler,
  handleAuthChange,
  hydrateUiState,
  renderAuthUi,
  updateHomeModeUi,
  syncRoute,
  initializeAuth,
  hydrateSets
}) {
  setAuthChangeHandler(handleAuthChange);
  hydrateUiState();
  renderAuthUi();
  updateHomeModeUi();
  syncRoute();
  void initializeAuth();
  hydrateSets();
}
